# -*- coding: utf-8 -*- 
"""resize_image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xb3Tj3j0VH6aV7YSdhFBRa4NYHUzF3Fe
"""

from PIL import Image

# Open the image
img = Image.open("/file/path/image")

# Define the coordinates of the top-left corner and bottom-right corner of the crop area
left, top = 0, 0
right, bottom = 712, 430 

# Crop the image using the coordinates
cropped_img = img.crop((left, top, right, bottom))

# Save the cropped image
cropped_img.save("/path/for/output/file")

"""# New Section"""
